# Generated by Django 5.1.4 on 2024-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(default='Sin descripcion', max_length=255),
        ),
    ]
